[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-Permitted-Cross-Domain-Policies = "none"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[context.production.environment]
  NODE_VERSION = "18"
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  REACT_APP_ENV = "preview"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
  REACT_APP_ENV = "development"
